{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.0.13.jar",
          "url": "spring-tx-6.0.13.jar",
          "size": 271165,
          "sha512": "2020ee6eab6ceb113dc665eba400bad9973c5eeeecfdb9c62b082cb543cbb6913e498b6c4c4dd644c183d82c37ca848eba5b6c81a88035bafaf1fa38de2929fb",
          "sha256": "229067fa4b4db30c334f96f165dccb5d7bc02628cfa7d2bb5957f2f07d047312",
          "sha1": "0182219d97469f459e0c44033d5dc5260d042cfb",
          "md5": "698d962001f22f397a1e472db2d5a49d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.0.13.jar",
          "url": "spring-tx-6.0.13.jar",
          "size": 271165,
          "sha512": "2020ee6eab6ceb113dc665eba400bad9973c5eeeecfdb9c62b082cb543cbb6913e498b6c4c4dd644c183d82c37ca848eba5b6c81a88035bafaf1fa38de2929fb",
          "sha256": "229067fa4b4db30c334f96f165dccb5d7bc02628cfa7d2bb5957f2f07d047312",
          "sha1": "0182219d97469f459e0c44033d5dc5260d042cfb",
          "md5": "698d962001f22f397a1e472db2d5a49d"
        }
      ]
    }
  ]
}
