{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.0.13.jar",
          "url": "spring-expression-6.0.13.jar",
          "size": 296590,
          "sha512": "985ef9db9776140cd86ce28580b7656b58672f8fb364bc6a643bac654f4851afd5bc46f096ee6e6339a3f124d946e0454a2cbce5e9e4cef1551bdefca673688c",
          "sha256": "f19030e588e91bb4ec8686c246a24eb7eef1ccccaa27a10da1e876b86cd96683",
          "sha1": "2bedffa4a3850bbbb652a31c47671824b17fbe01",
          "md5": "28c25d4e055b99ff2ae1af7a465958a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.0.13.jar",
          "url": "spring-expression-6.0.13.jar",
          "size": 296590,
          "sha512": "985ef9db9776140cd86ce28580b7656b58672f8fb364bc6a643bac654f4851afd5bc46f096ee6e6339a3f124d946e0454a2cbce5e9e4cef1551bdefca673688c",
          "sha256": "f19030e588e91bb4ec8686c246a24eb7eef1ccccaa27a10da1e876b86cd96683",
          "sha1": "2bedffa4a3850bbbb652a31c47671824b17fbe01",
          "md5": "28c25d4e055b99ff2ae1af7a465958a5"
        }
      ]
    }
  ]
}
